import {initNavigation} from './navigation.js';import {fetchProducts} from './products.js';import {cartCount} from './cart.js';import {isWishlisted,toggleWishlist} from './wishlist.js';import {money} from './utils.js';import {fetchCategories} from './categories.js';

function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]||c));}
export function renderCategories(container,categories){if(!container)return;if(!categories.length){container.innerHTML='<div class="empty">No categories available right now.</div>';return;}container.innerHTML=categories.map((c,i)=>`<a class="category-card tilt reveal" href="shop.html?category=${encodeURIComponent(c.name)}"><div class="category-card__copy"><span class="eyebrow" style="color:#fff">${String(i+1).padStart(2,'0')}</span><h2>${escapeHtml(c.name)}</h2><p>Shop ${escapeHtml(c.name)}.</p></div></a>`).join('');initMotion();}

export async function renderProducts(container,products){if(!container)return;container.innerHTML=products.map(p=>`<article class="product-card tilt reveal"><a href="product.html?id=${encodeURIComponent(p.id)}"><div class="product-media"><img loading="lazy" src="${p.image}" alt="${p.name}"><span class="product-badge">${p.sale_price?'Sale':p.new_arrival?'New':'Edit'}</span><button class="wish" data-wish="${p.id}" aria-label="Wishlist ${p.name}" type="button">${isWishlisted(p.id)?'♥':'♡'}</button></div><div class="product-info"><h3>${p.name}</h3><div class="price">${money(p.sale_price||p.price)} ${p.sale_price?`<del>${money(p.price)}</del>`:''}</div></div></a></article>`).join('');container.querySelectorAll('[data-wish]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();b.textContent=toggleWishlist(b.dataset.wish)?'♥':'♡'}));initMotion();}
function initMotion(){const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('is-visible')),{threshold:.08});document.querySelectorAll('.reveal:not(.is-visible)').forEach(e=>obs.observe(e));const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce)return;document.querySelectorAll('.tilt').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(900px) rotateX(${(-y*3).toFixed(2)}deg) rotateY(${(x*3).toFixed(2)}deg) translateY(-5px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});const hero=document.querySelector('.hero');hero?.addEventListener('pointermove',e=>{const x=(e.clientX/innerWidth-.5)*12,y=(e.clientY/innerHeight-.5)*8;hero.style.setProperty('--mx',x+'px');hero.style.setProperty('--my',y+'px');hero.querySelector('.hero-image')?.style.setProperty('--rx',(-x*.18)+'deg');hero.querySelector('.hero-image')?.style.setProperty('--ry',(y*.18)+'deg')});let t=0;setInterval(()=>{t+=.06;document.documentElement.style.setProperty('--float',Math.sin(t)*7+'px')},50)}
async function init(){await initNavigation();document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=cartCount());document.addEventListener('cart:updated',()=>document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=cartCount()));const [products,categories]=await Promise.all([fetchProducts(),fetchCategories()]);document.querySelectorAll('[data-product-grid]').forEach((g,i)=>renderProducts(g,i?products.slice(4,8):products.slice(0,4)));document.querySelectorAll('[data-category-grid]').forEach(g=>renderCategories(g,categories));initMotion();}
init();
