import {getSupabase} from './supabase.js';
export const demoProducts=[
{id:'demo-1',name:'Kashmir Wool Overshirt',slug:'kashmir-wool-overshirt',price:2999,sale_price:2499,category:'Layers',material:'Wool blend',sizes:['S','M','L','XL'],colors:['Forest','Black'],stock:14,featured:true,new_arrival:true,bestseller:true,image:'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=80'},
{id:'demo-2',name:'Everyday Relaxed Tee',slug:'everyday-relaxed-tee',price:1299,sale_price:null,category:'Everyday',material:'Cotton',sizes:['S','M','L','XL'],colors:['Ivory','Charcoal'],stock:32,featured:true,new_arrival:true,bestseller:false,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80'},
{id:'demo-3',name:'Textured Knit Polo',slug:'textured-knit-polo',price:2299,sale_price:1999,category:'Everyday',material:'Knit',sizes:['S','M','L'],colors:['Clay','Cream'],stock:11,featured:true,new_arrival:false,bestseller:true,image:'https://images.unsplash.com/photo-1627225924765-552d49cf47ad?auto=format&fit=crop&w=900&q=80'},
{id:'demo-4',name:'Modern Utility Jacket',slug:'modern-utility-jacket',price:3999,sale_price:null,category:'Layers',material:'Cotton twill',sizes:['M','L','XL'],colors:['Olive','Stone'],stock:8,featured:false,new_arrival:true,bestseller:false,image:'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80'},
{id:'demo-5',name:'Soft Drape Shirt',slug:'soft-drape-shirt',price:2199,sale_price:1799,category:'Occasion',material:'Viscose blend',sizes:['S','M','L','XL'],colors:['Sand','Black'],stock:17,featured:true,new_arrival:false,bestseller:true,image:'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=80'},
{id:'demo-6',name:'Crown Straight Trousers',slug:'crown-straight-trousers',price:2499,sale_price:null,category:'Everyday',material:'Cotton',sizes:['30','32','34','36'],colors:['Charcoal','Stone'],stock:22,featured:false,new_arrival:true,bestseller:false,image:'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80'},
{id:'demo-7',name:'Kashmir Layer Hoodie',slug:'kashmir-layer-hoodie',price:2799,sale_price:2399,category:'Layers',material:'Fleece',sizes:['S','M','L','XL'],colors:['Forest','Cream'],stock:9,featured:true,new_arrival:true,bestseller:true,image:'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80'},
{id:'demo-8',name:'Minimalist Co-ord Set',slug:'minimalist-co-ord-set',price:3499,sale_price:null,category:'Occasion',material:'Cotton blend',sizes:['S','M','L'],colors:['Stone','Olive'],stock:6,featured:true,new_arrival:false,bestseller:false,image:'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=900&q=80'}];
export async function fetchProducts(){const sb=getSupabase();if(!sb)return demoProducts.map(p=>({...p,images:[p.image]}));const {data,error}=await sb.from('products').select('*,categories(name),product_images(url,sort_order)').eq('status','active').order('created_at',{ascending:false});if(error){console.error('Could not load products from Supabase:',error);return [];}return (data||[]).map(p=>{const images=[...(p.product_images||[])].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(i=>i.url).filter(Boolean).slice(0,8);return {...p,category:p.categories?.name||'',images,image:images[0]||''};});}
export async function fetchProduct(id){const list=await fetchProducts();return list.find(p=>p.id===id||p.slug===id)||list[0];}
